const express = require('express');
const router = express.Router();

// PDF generation route
router.post('/generate', async (req, res) => {
  try {
      const { riadName, rooms, analysis, competitors, events, holidays, pricing } = req.body;

              if (!riadName || !analysis) {
                    return res.status(400).json({ error: 'Missing required data' });
                        }

                            // Build PDF content as HTML
                                const pdfContent = generatePDFContent({
                                      riadName,
                                            rooms,
                                                  analysis,
                                                        competitors,
                                                              events,
                                                                    holidays,
                                                                          pricing
                                                                              });

                                                                                  // Return HTML for client-side PDF generation
                                                                                      res.json({
                                                                                            success: true,
                                                                                                  html: pdfContent,
                                                                                                        filename: `RiadPricer_${riadName.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`
                                                                                                            });
                                                                                                              } catch (error) {
                                                                                                                  console.error('PDF generation error:', error);
                                                                                                                      res.status(500).json({ error: 'Failed to generate PDF' });
                                                                                                                        }
                                                                                                                        });
                                                                                                                        
                                                                                                                        function generatePDFContent({ riadName, rooms, analysis, competitors, events, holidays, pricing }) {
                                                                                                                          const date = new Date().toLocaleDateString('fr-FR', { year: 'numeric', month: 'long', day: 'numeric' });
                                                                                                                            
                                                                                                                              const competitorRows = (competitors || []).slice(0, 20).map(c => `
                                                                                                                                  <tr>
                                                                                                                                        <td>${c.name || 'N/A'}</td>
                                                                                                                                              <td>${c.quartier || 'N/A'}</td>
                                                                                                                                                    <td>${c.rooms || 'N/A'}</td>
                                                                                                                                                          <td>${c.rating || 'N/A'}/5</td>
                                                                                                                                                                <td>${c.price_low || 'N/A'} - ${c.price_high || 'N/A'} MAD</td>
                                                                                                                                                                    </tr>
                                                                                                                                                                      `).join('');
                                                                                                                                                                      
                                                                                                                                                                        const eventRows = (events || []).slice(0, 15).map(e => `
                                                                                                                                                                            <tr>
                                                                                                                                                                                  <td>${e.name || 'N/A'}</td>
                                                                                                                                                                                        <td>${e.date || 'N/A'}</td>
                                                                                                                                                                                              <td>${e.type || 'N/A'}</td>
                                                                                                                                                                                                    <td>${e.impact || 'Medium'}</td>
                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                          `).join('');
                                                                                                                                                                                                          
                                                                                                                                                                                                            return `
                                                                                                                                                                                                            <!DOCTYPE html>
                                                                                                                                                                                                            <html lang="fr">
                                                                                                                                                                                                            <head>
                                                                                                                                                                                                            <meta charset="UTF-8">
                                                                                                                                                                                                            <title>Rapport RiadPricer - ${riadName}</title>
                                                                                                                                                                                                            <style>
                                                                                                                                                                                                              body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
                                                                                                                                                                                                                h1 { color: #8B4513; text-align: center; border-bottom: 3px solid #8B4513; padding-bottom: 10px; }
                                                                                                                                                                                                                  h2 { color: #8B4513; margin-top: 30px; border-left: 4px solid #D4A853; padding-left: 10px; }
                                                                                                                                                                                                                    h3 { color: #555; }
                                                                                                                                                                                                                      table { width: 100%; border-collapse: collapse; margin: 15px 0; }
                                                                                                                                                                                                                        th { background: #8B4513; color: white; padding: 10px; text-align: left; }
                                                                                                                                                                                                                          td { padding: 8px; border-bottom: 1px solid #ddd; }
                                                                                                                                                                                                                            tr:nth-child(even) { background: #f9f6f0; }
                                                                                                                                                                                                                              .header-info { display: flex; justify-content: space-between; margin: 20px 0; }
                                                                                                                                                                                                                                .info-box { background: #f9f6f0; padding: 15px; border-radius: 8px; flex: 1; margin: 5px; }
                                                                                                                                                                                                                                  .price-highlight { background: #8B4513; color: white; padding: 20px; border-radius: 8px; text-align: center; margin: 20px 0; }
                                                                                                                                                                                                                                    .price-highlight h2 { color: white; border: none; }
                                                                                                                                                                                                                                      .price-highlight .price { font-size: 2em; font-weight: bold; }
                                                                                                                                                                                                                                        .footer { text-align: center; margin-top: 40px; color: #888; border-top: 1px solid #ddd; padding-top: 20px; }
                                                                                                                                                                                                                                          .badge { display: inline-block; padding: 3px 8px; border-radius: 12px; font-size: 0.8em; font-weight: bold; }
                                                                                                                                                                                                                                            .badge-high { background: #ff6b6b; color: white; }
                                                                                                                                                                                                                                              .badge-medium { background: #ffd93d; color: #333; }
                                                                                                                                                                                                                                                .badge-low { background: #6bcb77; color: white; }
                                                                                                                                                                                                                                                </style>
                                                                                                                                                                                                                                                </head>
                                                                                                                                                                                                                                                <body>
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                <h1>🏡 Rapport d'Analyse de Prix - RiadPricer</h1>
                                                                                                                                                                                                                                                <p style="text-align:center; color: #888;">Généré le ${date}</p>
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                <div class="header-info">
                                                                                                                                                                                                                                                  <div class="info-box">
                                                                                                                                                                                                                                                      <h3>Votre Riad</h3>
                                                                                                                                                                                                                                                          <p><strong>Nom:</strong> ${riadName}</p>
                                                                                                                                                                                                                                                              <p><strong>Chambres:</strong> ${rooms || 'N/A'}</p>
                                                                                                                                                                                                                                                                  <p><strong>Quartier:</strong> ${analysis?.quartier || 'N/A'}</p>
                                                                                                                                                                                                                                                                      <p><strong>Catégorie:</strong> ${analysis?.category || 'N/A'}</p>
                                                                                                                                                                                                                                                                          <p><strong>Prix actuel:</strong> ${analysis?.currentPrice || 'N/A'} MAD/nuit</p>
                                                                                                                                                                                                                                                                              <p><strong>Note:</strong> ${analysis?.rating || 'N/A'}/5 (${analysis?.reviewCount || 0} avis)</p>
                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                  <div class="info-box">
                                                                                                                                                                                                                                                                                      <h3>Résumé de l'Analyse</h3>
                                                                                                                                                                                                                                                                                          <p><strong>Concurrents analysés:</strong> ${(competitors || []).length}</p>
                                                                                                                                                                                                                                                                                              <p><strong>Événements trouvés:</strong> ${(events || []).length}</p>
                                                                                                                                                                                                                                                                                                  <p><strong>Périodes analysées:</strong> ${(holidays || []).length} pays</p>
                                                                                                                                                                                                                                                                                                      <p><strong>Facteur saisonnalité:</strong> ${pricing?.seasonalityFactor?.toFixed(2) || '1.00'}x</p>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                        <div class="price-highlight">
                                                                                                                                                                                                                                                                                                          <h2>💰 Prix Recommandé</h2>
                                                                                                                                                                                                                                                                                                            <div class="price">${pricing?.recommendedPrice || 'N/A'} MAD/nuit</div>
                                                                                                                                                                                                                                                                                                              <p>Fourchette: ${pricing?.priceRange?.min || 'N/A'} - ${pricing?.priceRange?.max || 'N/A'} MAD</p>
                                                                                                                                                                                                                                                                                                                <p>${pricing?.strategy || 'Prix basé sur analyse concurrentielle et événements locaux'}</p>
                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                <h2>📊 Analyse Concurrentielle (${(competitors || []).length} Riads)</h2>
                                                                                                                                                                                                                                                                                                                <table>
                                                                                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                                                                      <tr>
                                                                                                                                                                                                                                                                                                                            <th>Nom du Riad</th>
                                                                                                                                                                                                                                                                                                                                  <th>Quartier</th>
                                                                                                                                                                                                                                                                                                                                        <th>Chambres</th>
                                                                                                                                                                                                                                                                                                                                              <th>Note</th>
                                                                                                                                                                                                                                                                                                                                                    <th>Fourchette de Prix</th>
                                                                                                                                                                                                                                                                                                                                                        </tr>
                                                                                                                                                                                                                                                                                                                                                          </thead>
                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                ${competitorRows || '<tr><td colspan="5">Aucun concurrent trouvé</td></tr>'}
                                                                                                                                                                                                                                                                                                                                                                  </tbody>
                                                                                                                                                                                                                                                                                                                                                                  </table>
                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                  <h2>📅 Événements à Marrakech</h2>
                                                                                                                                                                                                                                                                                                                                                                  <table>
                                                                                                                                                                                                                                                                                                                                                                    <thead>
                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                              <th>Événement</th>
                                                                                                                                                                                                                                                                                                                                                                                    <th>Date</th>
                                                                                                                                                                                                                                                                                                                                                                                          <th>Type</th>
                                                                                                                                                                                                                                                                                                                                                                                                <th>Impact</th>
                                                                                                                                                                                                                                                                                                                                                                                                    </tr>
                                                                                                                                                                                                                                                                                                                                                                                                      </thead>
                                                                                                                                                                                                                                                                                                                                                                                                        <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                            ${eventRows || '<tr><td colspan="4">Aucun événement trouvé</td></tr>'}
                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                              </table>
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                              <h2>📈 Stratégie de Prix</h2>
                                                                                                                                                                                                                                                                                                                                                                                                              <p>${pricing?.strategy || 'N/A'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                              <h2>💡 Recommandations</h2>
                                                                                                                                                                                                                                                                                                                                                                                                              ${(pricing?.recommendations || []).map(r => `<p>• ${r}</p>`).join('') || '<p>Optimisez votre prix en fonction des événements locaux et de la saison.</p>'}
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                              <div class="footer">
                                                                                                                                                                                                                                                                                                                                                                                                                <p>Rapport généré par <strong>RiadPricer</strong> - L'outil d'optimisation de prix pour les riads de Marrakech</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p>© ${new Date().getFullYear()} RiadPricer. Tous droits réservés.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  </body>
                                                                                                                                                                                                                                                                                                                                                                                                                  </html>`;
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  module.exports = router;
